* Disable multiprocessor compilation because of error C2813. * Add new file XmlOptionsManager.h, which elevates the XML part of COptionsData to its own new class, CXmlOptionsManager. * Move #import declaration into XmlOptionsManager.h. * Rename OptionsDataXml.cpp to XmlOptionsManager.cpp to match new class's name.